sudo: false

language: node_js

cache:
  directories:
      - node_modules

jobs:
  include:
      - stage: lint
        node_js: "stable"
        script: npm run lint
      - stage: test
        node_js: "stable"
        script: npm test
